navikt/su-pdfgen

- data/supdfgen/vedtakInnvilgelse.json
- templates/supdfgen/partials/base.hbs
- templates/supdfgen/partials/innvilgelseBase.hbs
- templates/supdfgen/vedtakInnvilgelse.hbs
Støtter beregning i oppsatt regnestykke, m.m.
> Vedtaksbrev innvilgelse

- data/supdfgen/vedtakAvslag.json
- data/supdfgen/vedtakInnvilgelse.json
- templates/supdfgen/partials/base.hbs
- templates/supdfgen/partials/beregning.hbs
- templates/supdfgen/partials/flereAvslagsgrunner.hbs
- templates/supdfgen/vedtakInnvilgelse.hbs
Co-authored-by: Jacob Meidell <jacob.meidell@nav.no>
> Show full beregning in vedtaksbrev

- data/supdfgen/vedtakInnvilgelse.json
- templates/supdfgen/partials/base.hbs
- templates/supdfgen/partials/beregning.hbs
https://github.com/navikt/su-se-bakover/pull/164
> Show details about utenlandsk inntekt in beregning

- data/supdfgen/opphørsvedtak.json
- data/supdfgen/revurderingAvInntekt.json
- data/supdfgen/vedtakAvslag.json
- data/supdfgen/vedtakIngenEndring.json
- data/supdfgen/vedtakInnvilgelse.json
- templates/supdfgen/partials/beregning.hbs
> Vis dato for siste relevante sats-/G-endring

- data/supdfgen/vedtakInnvilgelse.json
- templates/supdfgen/partials/beregning.hbs
Co-authored-by: Aryan Iranzamini <aryan.iranzamini@nav.no>
Co-authored-by: Richard Martinsen <richard.martinsen@nav.no>
> begrens tekst om IEU mindre enn 1

- data/supdfgen/opphørsvedtak.json
- templates/supdfgen/opphørsvedtak.hbs
- templates/supdfgen/vedtakAvslag.hbs
tilhørende bakover PR: https://github.com/navikt/su-se-bakover/pull/310
> Opphørsgrunn for uføre vilkåret

- templates/supdfgen/avvistSøknadFritekst.hbs
- templates/supdfgen/forhåndsvarsel.hbs
- templates/supdfgen/partials/avslagBase.hbs
- templates/supdfgen/partials/fellesInfo.hbs
- templates/supdfgen/partials/hilsen.hbs
- templates/supdfgen/partials/innvilgelseBase.hbs
- templates/supdfgen/søknadTrukket.hbs
Flyttet også hilsenen og fellesinfo i avslag/innvilgelse inn i egne partials
> Endre til riktig telefonnummer i brevene

- data/supdfgen/vedtakIngenEndring.json
- templates/supdfgen/vedtakIngenEndring.hbs
Avhenger av https://github.com/navikt/su-se-bakover/pull/367
> Bruk gjeldende månedsutbetaling i ingen-endring-brevet

- templates/supdfgen/partials/base.hbs
- templates/supdfgen/partials/ekstraInnvilgelsesinformasjon.hbs
- templates/supdfgen/partials/innvilgelseBase.hbs
Ny informasjon skal legges til som "vedlegg" i brevet når en søknad blir innvilget.
> Legg til ekstra informasjon ved innvilgelse av søknad

- templates/supdfgen/partials/fellesInfo.hbs
- templates/supdfgen/partials/innvilgelseBase.hbs
La også på lenke-tag på de resterende lenkene, siden vi har begynt med dette i ekstrainformasjonen ved innvilgelse.
> Endre link til supplerende stønad uføre (istedet for alder)

- templates/supdfgen/opphørsvedtak.hbs
Flyttet også fritekst iht. fags ønsker.
> Vis opphørsparagrafer i opphørsbrev

- templates/supdfgen/soknad.hbs
Henger sammen med https://github.com/navikt/su-se-bakover/pull/728 og https://github.com/navikt/su-se-framover/pull/1634.
> Fjern innslag om sosialstønad i søknads-PDF

- data/supdfgen/forhåndsvarselTilbakekreving.json
- data/supdfgen/opphørMedTilbakekreving.json
- data/supdfgen/revurderingMedTilbakekreving.json
- templates/supdfgen/forhåndsvarselTilbakekreving.hbs
- templates/supdfgen/opphørMedTilbakekreving.hbs
- templates/supdfgen/opphørsvedtak.hbs
- templates/supdfgen/partials/base.hbs
- templates/supdfgen/partials/fnr.hbs
- templates/supdfgen/partials/opphør.hbs
- templates/supdfgen/partials/tilbakekrevingTabell.hbs
- templates/supdfgen/revurderingMedTilbakekreving.hbs
[ForhåndsvarselTilbakekreving.pdf](https://github.com/navikt/su-pdfgen/files/8324581/ForhandsvarselTilbakekreving.pdf)
[ForhåndsvarselTilbakekrevingOpphør.pdf](https://github.com/navikt/su-pdfgen/files/8324582/ForhandsvarselTilbakekrevingOpphor.pdf)
[VedtakTilbakekreving.pdf](https://github.com/navikt/su-pdfgen/files/8324583/VedtakTilbakekreving.pdf)
[VedtakTilbakekrevingOpphør.pdf](https://github.com/navikt/su-pdfgen/files/8324585/VedtakTilbakekrevingOpphor.pdf)
> Tilbakekrevingbrev

- templates/supdfgen/forhåndsvarselTilbakekreving.hbs
Ref ønske fra John Are
[forhåndsvarselTilbakekreving.pdf](https://github.com/navikt/su-pdfgen/files/8389830/forhandsvarselTilbakekreving.pdf)
> Endre tekst på forhåndsvarsel tilbakekreving

- data/supdfgen/opphørsvedtak.json
- data/supdfgen/revurderingAvInntekt.json
- data/supdfgen/revurderingMedTilbakekreving.json
- data/supdfgen/vedtakAvslag.json
- data/supdfgen/vedtakIngenEndring.json
- data/supdfgen/vedtakInnvilgelse.json
- templates/supdfgen/partials/base.hbs
- templates/supdfgen/partials/beregning.hbs
- templates/supdfgen/partials/satsoversikt.hbs
Se: https://github.com/navikt/su-se-bakover/pull/795
> Vis vurdering av bosituasjon/sats med tilhørende sats per periode i brev

- templates/supdfgen/partials/ekstraInnvilgelsesinformasjon.hbs
Ref: https://trello.com/c/LVK6CgRR/1239-endre-tekst-i-vedleggsdelen-i-innvilgelsesvedtak-da-teksten-ikke-gir-noe-mening
> Endre tekst i vedleggsdelen i innvilgelsesvedtak

- templates/supdfgen/alderHarIkkeBrevEnda.hbs
Brevet er ikke veldig detaljert
> Legger til et fallbackbrev for alder

- .github/workflows/branch.yml
- .github/workflows/master.yml
- .github/workflows/prod-deploy.yml
- .gitignore
- Dockerfile
Legger også til bin i gitignore
> Bytter til ghcr.io for imagerepo

- templates/supdfgen/partials/opphør.hbs
Legger til nye opphørsgrunner som følge av nye revurderinger
> Nye opphørsgrunner med nye revurderinger

- data/supdfgen/skattegrunnlag.json
- templates/supdfgen/skattegrunnlag.hbs
- templates/supdfgen/skattemelding/forNav.hbs
https://github.com/navikt/su-se-framover/pull/3063
https://github.com/navikt/su-se-bakover/pull/1492
> støtte for begrunnelse for skatt & gjør behandlingsId + vedtaksId nullable

- README.md
- templates/supdfgen/opphørsvedtak.hbs
- templates/supdfgen/partials/beregning.hbs
Må merges sammen med su-se-bakover + su-se-bakover
> Fjern avkorting

- templates/supdfgen/opphørsvedtak.hbs
- templates/supdfgen/partials/opphør.hbs
Kun endret mal for opphør da revurdering var ok slik den var.
> Revurdering alder
